import { createStudentWithGuardians } from '../createStudent.js';

// Converts one ImportRecord's staged mappedData into a real Student (+
// Guardian/User as applicable) via the exact same shared function the
// manual POST /students route uses (PRD/TRD §18.1) — an imported student
// is indistinguishable from a manually created one.
//
// Throws on failure (missing class, race-condition duplicate, etc.);
// callers catch per-row so one bad row never aborts the rest of the batch
// (PRD/TRD §2 / §6: partial commit failure is isolated per row).
export async function commitImportRecord(prisma, record) {
  const m = record.mappedData;

  if (!m.matchedClassId) {
    const err = new Error('No class selected for this row.');
    err.statusCode = 400;
    throw err;
  }
  // Date of birth is optional — this school doesn't collect it at
  // enrollment, so its absence is expected, not a failure.

  const guardians = [];
  if (m.matchedGuardianId) {
    guardians.push({
      guardianId: m.matchedGuardianId,
      relationship: m.guardianRelationship || 'GUARDIAN',
      isPrimary: true,
    });
  } else if (m.guardianFirstName && m.guardianLastName && m.guardianPhone) {
    guardians.push({
      firstName: m.guardianFirstName,
      lastName: m.guardianLastName,
      phone: m.guardianPhone,
      email: m.guardianEmail || undefined,
      relationship: m.guardianRelationship || 'GUARDIAN',
      isPrimary: true,
    });
  }
  // Rows with no guardian info commit with an empty guardians array —
  // createStudentWithGuardians's for-loop simply doesn't run. This school
  // doesn't collect guardian info at enrollment; it's never required.

  return prisma.$transaction((tx) =>
    createStudentWithGuardians(tx, {
      // No admissionNumber here, deliberately — this school doesn't track
      // admission/serial numbers, and nothing in the import pipeline
      // collects one anymore (see fieldDictionary.js). Always
      // auto-generated by createStudentWithGuardians, same as a manually
      // created student — an imported student is indistinguishable from
      // one entered by hand, including this.
      firstName: m.firstName,
      lastName: m.lastName,
      otherNames: m.otherNames || undefined,
      dateOfBirth: m.dateOfBirth ? new Date(m.dateOfBirth) : undefined,
      gender: m.gender,
      currentClassId: m.matchedClassId,
      guardians,
    }),
  );
}
