import { FileParseError, ScannedPdfError } from './importErrors.js';
import { groupIntoRows, assignToColumns, findHeaderRowIndex } from './tableReconstruction.js';

const MAX_ROWS = 1000;
const MAX_PAGES = 20; // PRD/TRD §15

// pdfjs-dist is used directly rather than the popular `pdf-parse` wrapper
// package: pdf-parse bundles pdf.js v1.10.100 (2018-era), which throws
// "bad XRef entry" on standards-compliant PDFs from modern tools —
// confirmed against PDFs generated by both Pillow and img2pdf during
// development. A Phase 2 extractor that fails on ordinary modern PDFs
// isn't fit for purpose, so this imports pdfjs-dist's current release
// directly instead.
async function loadPdfjs() {
  return import('pdfjs-dist/legacy/build/pdf.mjs');
}

export async function parsePdfTextTable(buffer) {
  let pdfjsLib;
  let doc;
  try {
    pdfjsLib = await loadPdfjs();
    const data = new Uint8Array(buffer);
    doc = await pdfjsLib.getDocument({
      data,
      useWorkerFetch: false,
      isEvalSupported: false,
      disableFontFace: true,
    }).promise;
  } catch {
    throw new FileParseError(
      'We couldn\u2019t read this PDF. It may be corrupted, password-protected, or in an unsupported format.',
    );
  }

  if (doc.numPages > MAX_PAGES) {
    throw new FileParseError(
      `This PDF has ${doc.numPages} pages, which is over the ${MAX_PAGES}-page limit per import. Please split it into smaller files.`,
    );
  }

  // A naive "split each line on whitespace" approach does not work for
  // PDFs: a table cell's text is a single positioned run with no
  // delimiter before the next cell's run — confirmed empirically against
  // a real Word→PDF export. Positioned items are read here and handed to
  // the shared column-anchored reconstruction (tableReconstruction.js).
  const items = [];
  try {
    for (let pageNum = 1; pageNum <= doc.numPages; pageNum++) {
      const page = await doc.getPage(pageNum);
      const textContent = await page.getTextContent();
      for (const item of textContent.items) {
        const text = item.str;
        if (!text || !text.trim()) continue;
        items.push({ text: text.trim(), x: item.transform[4], y: item.transform[5] });
      }
    }
  } catch {
    throw new FileParseError('We couldn\u2019t read the contents of this PDF.');
  }

  if (items.length === 0) {
    // No extractable text at all — a scanned/photographed document.
    // extract.js catches ScannedPdfError specifically and falls back to
    // the OCR path (Phase 3) instead of failing outright.
    throw new ScannedPdfError(
      'This PDF doesn\u2019t contain selectable text \u2014 it looks like a scanned document.',
    );
  }

  // PDF space has y increasing *upward* — rows sort top-to-bottom by
  // descending y.
  const rows = groupIntoRows(items, { ySortDescending: true });

  const headerRowIndex = findHeaderRowIndex(rows);
  if (headerRowIndex === -1) {
    throw new FileParseError(
      'We couldn\u2019t find a table in this PDF. Please make sure your student list is formatted as a table (like the downloadable template), or upload it as Excel/CSV instead.',
    );
  }

  const headerRow = rows[headerRowIndex];
  const columnAnchors = headerRow.items.map((i) => i.x);
  const headers = headerRow.items.map((i) => i.text);

  const dataRows = rows
    .slice(headerRowIndex + 1)
    .filter((row) => row.items.length > 0)
    .map((row) => assignToColumns(row.items, columnAnchors));

  if (dataRows.length === 0) {
    throw new FileParseError('This PDF has headers but no student rows underneath them.');
  }
  if (dataRows.length > MAX_ROWS) {
    throw new FileParseError(
      `This file has ${dataRows.length} rows, which is over the ${MAX_ROWS}-row limit per import. Please split it into smaller files.`,
    );
  }

  const objectRows = dataRows.map((cells) => {
    const obj = {};
    headers.forEach((header, i) => {
      obj[header] = cells[i] !== undefined ? cells[i] : '';
    });
    return obj;
  });

  return { headers, rows: objectRows };
}
