import { FileParseError } from './importErrors.js';

const MAX_ROWS = 1000;
const MAX_PAGES = 20; // PRD/TRD §15

// pdfjs-dist is used directly rather than the popular `pdf-parse` wrapper
// package: pdf-parse bundles pdf.js v1.10.100 (2018-era), which throws
// "bad XRef entry" on standards-compliant PDFs from modern tools —
// confirmed against PDFs generated by both Pillow and img2pdf during
// development. A Phase 2 extractor that fails on ordinary modern PDFs
// isn't fit for purpose, so this imports pdfjs-dist's current release
// directly instead.
async function loadPdfjs() {
  return import('pdfjs-dist/legacy/build/pdf.mjs');
}

// A naive "split each line on whitespace" approach does not work for
// PDFs: a table cell's text is a single positioned run with no delimiter
// before the next cell's run — confirmed empirically against a real
// Word→PDF export. This extractor reads pdf.js's raw positioned text
// items per page and reconstructs the table using the header row's
// x-positions as column anchors — every item is assigned to the column
// of its nearest anchor, robust to per-cell text being left-aligned,
// right-aligned, or split across multiple runs.
const ROW_Y_TOLERANCE = 3;

function groupIntoRows(items) {
  const sorted = [...items].sort((a, b) => b.y - a.y || a.x - b.x);
  const rows = [];

  for (const item of sorted) {
    const row = rows.find((r) => Math.abs(r.y - item.y) <= ROW_Y_TOLERANCE);
    if (row) {
      row.items.push(item);
    } else {
      rows.push({ y: item.y, items: [item] });
    }
  }

  return rows.map((r) => ({ ...r, items: r.items.sort((a, b) => a.x - b.x) }));
}

// Assigns each item in a row to the header column whose anchor x is
// closest, then joins same-column items (in left-to-right order) with a
// space — this correctly reassembles a cell whose text arrived as
// multiple runs (e.g. bold+regular spans within one cell).
function assignToColumns(rowItems, columnAnchors) {
  const cells = columnAnchors.map(() => []);
  for (const item of rowItems) {
    let closestIndex = 0;
    let closestDistance = Infinity;
    columnAnchors.forEach((anchorX, i) => {
      const distance = Math.abs(item.x - anchorX);
      if (distance < closestDistance) {
        closestDistance = distance;
        closestIndex = i;
      }
    });
    cells[closestIndex].push(item);
  }
  return cells.map((cellItems) => cellItems.map((i) => i.text).join(' ').trim());
}

export async function parsePdfTextTable(buffer) {
  let pdfjsLib;
  let doc;
  try {
    pdfjsLib = await loadPdfjs();
    const data = new Uint8Array(buffer);
    doc = await pdfjsLib.getDocument({
      data,
      useWorkerFetch: false,
      isEvalSupported: false,
      disableFontFace: true,
    }).promise;
  } catch {
    throw new FileParseError(
      'We couldn\u2019t read this PDF. It may be corrupted, password-protected, or in an unsupported format.',
    );
  }

  if (doc.numPages > MAX_PAGES) {
    throw new FileParseError(
      `This PDF has ${doc.numPages} pages, which is over the ${MAX_PAGES}-page limit per import. Please split it into smaller files.`,
    );
  }

  const items = [];
  try {
    for (let pageNum = 1; pageNum <= doc.numPages; pageNum++) {
      const page = await doc.getPage(pageNum);
      const textContent = await page.getTextContent();
      for (const item of textContent.items) {
        const text = item.str;
        if (!text || !text.trim()) continue;
        items.push({ text: text.trim(), x: item.transform[4], y: item.transform[5] });
      }
    }
  } catch {
    throw new FileParseError('We couldn\u2019t read the contents of this PDF.');
  }

  if (items.length === 0) {
    // No extractable text at all — this is the scanned/image-based PDF
    // case. Phase 2 is deterministic-text-only; OCR is Phase 3 and isn't
    // built yet, so this fails clearly rather than silently producing
    // nothing (PRD/TRD §3: extraction method escalates by phase, and a
    // phase that isn't built yet must say so, not guess).
    throw new FileParseError(
      'This PDF doesn\u2019t contain selectable text \u2014 it looks like a scanned document. Scanned PDFs aren\u2019t supported yet; please upload an Excel, CSV, or Word file instead, or a PDF exported directly from a spreadsheet/document (not a scan).',
    );
  }

  const rows = groupIntoRows(items);

  // A plain paragraph line (e.g. a document title above the table) is a
  // single positioned text item; a real table row has one item per
  // column. Skip any leading single-item lines rather than assuming the
  // very first line is the header.
  const headerRowIndex = rows.findIndex((r) => r.items.length >= 2);
  if (headerRowIndex === -1) {
    throw new FileParseError(
      'We couldn\u2019t find a table in this PDF. Please make sure your student list is formatted as a table (like the downloadable template), or upload it as Excel/CSV instead.',
    );
  }

  const headerRow = rows[headerRowIndex];
  const columnAnchors = headerRow.items.map((i) => i.x);
  const headers = headerRow.items.map((i) => i.text);

  const dataRows = rows
    .slice(headerRowIndex + 1)
    .filter((row) => row.items.length > 0)
    .map((row) => assignToColumns(row.items, columnAnchors));

  if (dataRows.length === 0) {
    throw new FileParseError('This PDF has headers but no student rows underneath them.');
  }
  if (dataRows.length > MAX_ROWS) {
    throw new FileParseError(
      `This file has ${dataRows.length} rows, which is over the ${MAX_ROWS}-row limit per import. Please split it into smaller files.`,
    );
  }

  const objectRows = dataRows.map((cells) => {
    const obj = {};
    headers.forEach((header, i) => {
      obj[header] = cells[i] !== undefined ? cells[i] : '';
    });
    return obj;
  });

  return { headers, rows: objectRows };
}
